GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJaZWxkaWFudG8iLCJlbWFpbCI6InplbEBnbWFpbC5jb20iLCJpYXQiOjE2NjM0MDMzNTUsImV4cCI6MTY2MzQwMzM2NX0.NkrcshTSuxsetMrTWvV2smg6zH13V53QC2i6vH4QQ2E
###
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Zeldianto",
    "email": "zel@gmail.com",
    "password": "123"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "zel@gmail.com",
    "password": "123"
}

###
GET http://localhost:8000/refresh-token